{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0", 
    "title": "DAVO Rest Api",
    "description": "Documentation REST API for DAVO"
  },
  "host": "192.168.2.8:3000",
  "basePath": "/api/v1/",
  "paths": {
    "/doctor": {
      "get": {
        "tags": ["Doctor"],
        "summary": "Get all doctors",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "data": {
                "type":"array",
                  "items": {
                    "properties": {
                      "_id": {
                        "type": "integer",
                        "uniqueItems": true,
                        "autoIncrement": true
                      },
                      "name": {
                        "type": "string",
                        "maxLength": 50
                      },
                      "surname": {
                        "type": "string",
                        "maxLength": 50
                      },
                      "phone": {
                        "type": "string",
                        "maxLength": 50
                      },
                      "hospital": {
                        "type": "string"
                      },
                      "doctor_type": {
                        "type": "integer"
                      },
                      "createdAt": {
                        "type": "string"
                      },
                      "updatedAt": {
                        "type": "string"
                      }
                    }
                  }
                }
              },
              "example": {
                "data": [
                  {
                    "id": 3,
                    "name": "Henry",
                    "surname": "Bren",
                    "phone": "+998991234567",
                    "hospital": "Safo Tibbiyot",
                    "doctor_type": 1,
                    "createdAt": "2022-05-20T10:09:40.000Z",
                    "updatedAt": "2022-05-20T10:09:40.000Z"
                  },
                  {
                    "id": 4,
                    "name": "Nodir",
                    "surname": "Navruzov",
                    "phone": "+998991234568",
                    "hospital": "Safo Tibbiyot",
                    "doctor_type": 1,
                    "createdAt": "2022-05-20T12:01:15.000Z",
                    "updatedAt": "2022-05-20T12:01:15.000Z"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Error not found",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "Error": "No doctor found"
              }
            }
          }
        }
      }
    },
    "/doctor/by-id": {
      "get": {
        "tags": ["Doctor"],
        "summary": "Get doctor by ID",
        "parameters": [{
          "required":["id"],
          "in": "qeury",
          "name": "id"
        }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "_id": {
                  "type": "integer",
                  "uniqueItems": true,
                  "autoIncrement": true
                },
                "name": {
                  "type": "string",
                  "maxLength": 50
                },
                "surname": {
                  "type": "string",
                  "maxLength": 50
                },
                "phone": {
                  "type": "string",
                  "maxLength": 50
                },
                "hospital": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                },
                "doctor_type": {
                  "type": "integer"
                } 
              },
              "example": {
                  "id": 3,
                  "name": "Henry",
                  "surname": "Bren",
                  "phone": "+998991234567",
                  "hospital": "Safo Tibbiyot",
                  "password": "$2b$10$OCeHq$2sh/Ds6xsdaqcDDBunzl1/1KDojXC.lsSCOd4tkz1qasd0Qfa",
                  "doctor_type": 1,
                  "createdAt": "2022-05-20T10:09:40.000Z",
                  "updatedAt": "2022-05-20T10:09:40.000Z"
              }
            }
          },
          "404": {
            "description": "Error not found",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "Error": "Doctor not found"
              }
            }
          }
        }
      }
    },
    "/doctor/register": {
      "post": {
        "tags": ["Doctor"],
        "summary": "Register",
        "consumes": "application/json",
        "parameters":[{
          "required":["phone", "password", "name", "surname", "hospital", "doctor_type"],
          "in": "body",
          "description": "Register doctor",
          "schema": {
            "properties": {
              "name": {
                "type": "string",
                "maxLength": 50
              },
              "surname": {
                "type": "string",
                "maxLength": 50
              },
              "phone": {
                "type": "string",
                "maxLength": 50
              },
              "hospital": {
                "type": "string"
              },
              "password": {
                "type": "string"
              },
              "doctor_type": {
                "type": "integer",
                "foreignKey": "id"
              } 
            },
            "example": {
              "name": "Henry",
              "surname": "Bren",
              "phone": "+998991234567",
              "hospital": "Shox Med Center",
              "password": "mypassword123",
              "doctor_type": 1
            }
          }
        }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "data": {
                  "properties": {
                    "_id": {
                      "type": "integer",
                      "uniqueItems": true,
                      "autoIncrement": true
                    },
                    "name": {
                      "type": "string",
                      "maxLength": 50
                    },
                    "surname": {
                      "type": "string",
                      "maxLength": 50
                    },
                    "phone": {
                      "type": "string",
                      "maxLength": 50
                    },
                    "hospital": {
                      "type": "string"
                    },
                    "doctor_type": {
                      "type": "integer"
                    }
                  }
                },
                "message": {
                  "type": "string"
                }
              },
              "example": {
                  "data" : {
                    "id": 5,
                    "name": "Henry",
                    "surname": "Bren",
                    "phone": "+998991234567",
                    "hospital": "Shox Med Center",
                    "doctor_type": 1,
                    "updatedAt": "2022-05-23T11:17:20.493Z",
                    "createdAt": "2022-05-23T11:17:20.493Z"
                  },
                  "message": "Doctor: Henry Bren successfully created"
              }
            }
          },
          "400": {
            "description": "Validation error",
              "schema": {
                "properties": {
                  "errors": {
                  "type":"array",
                    "items": {
                      "properties": {
                        "key": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "errors": [
                    {
                      "name": "Invalid value"
                    },
                    {
                      "phone": "Invalid value"
                    }
                  ]
                }
              }
          },
          "409": {
            "description": "Conflict, if Doctor allready exsists",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "message": "Doctor: Nodir Navruzov allready exsists"
              }
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "error": "Something wrong"
              }
            }
          }
        }
      }
    },
    "/doctor/login": {
      "post": {
        "tags": ["Doctor"],
        "summary": "Login",
        "parameters":[{
          "in": "body",
          "required":["phone", "password"],
          "description": "Login doctor",
          "schema": {
            "properties": {
              "phone": {
                "type": "string"
              },
              "password": {
                "type":"string"
              }
            },
            "example": {
              "phone": "+998991234567",
              "password": "mypassword123"
            }
          }
        }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "data": {
                  "properties": {
                    "_id": {
                      "type": "integer",
                      "uniqueItems": true,
                      "autoIncrement": true
                    },
                    "name": {
                      "type": "string",
                      "maxLength": 50
                    },
                    "surname": {
                      "type": "string",
                      "maxLength": 50
                    },
                    "phone": {
                      "type": "string",
                      "maxLength": 50
                    },
                    "hospital": {
                      "type": "string"
                    },
                    "doctor_type": {
                      "type": "integer"
                    }
                  }
                },
                "token": {
                  "type": "string"
                }
              },
              "example": {
                "data": {
                  "_id": 1,
                  "name": "Nodir",
                  "surname": "Navruzov",
                  "phone": "+998991234567",
                  "hospital": "Safo Tibbiyot",
                  "doctor_type": "LOR"
                },
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTI0Mjk5NzQsImV4cCI6MTY1MjQ3MzE3NH0.TnGw93yRJZ7egOu2Ea5kxI3sHb-ZYPKTdGxhr9XZ6z0"
              }
            }
          },
          "401": {
            "description": "Phone or password wrong",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "message": "Phone or password wrong"
              }
            }
          },
          "400": {
            "description": "Validation error",
              "schema": {
                "properties": {
                  "errors": {
                  "type":"array",
                    "items": {
                      "properties": {
                        "phone": {
                          "type": "string"
                        },
                        "password": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "errors": [
                    {
                      "phone": "Invalid value"
                    },
                    {
                      "password": "Invalid value"
                    }
                  ]
                }
              }
          }
        }
      }
    },
    "/doctor/type/by-name": {
      "get": {
        "tags": ["Doctor"],
        "summary": "Get doctor type by name",
        "parameters": [{
          "in": "qeury",
          "name": "name"
        }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "id": {
                  "type": "integer"
                },
                "type": {
                  "type": "string"
                }
              },
              "example": {
                "id": 1,
                "type": "Stomatolog"
              }
            }
          },
          "404": {
            "description": "Error not found",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "Error": "Doctor type not found"
              }
            }
          },
          "400": {
            "description": "Validation error",
              "schema": {
                "properties": {
                  "errors": {
                  "type":"array",
                    "items": {
                      "properties": {
                        "name": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "errors": [
                    {
                      "name": "Invalid value"
                    }
                  ]
                }
              }
          }
        }
      }
    },
    "/doctor/type/create": {
      "post": {
        "tags": ["Doctor"],
        "summary": "Login",
        "parameters":[{
          "in": "body",
          "required":["name"],
          "description": "Login doctor",
          "schema": {
            "properties": {
              "name": {
                "type": "string"
              }
            },
            "example": {
              "name": "Oncologists"
            }
          }
        }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "type": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type":"string"
                    },
                    "updatedAt": {
                      "type":"string"
                    },
                    "createdAt": {
                      "type":"string"
                    }
                  },
                  "message": "Type LOR successfully created"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "error": "Something wrong"
              }
            }
          }
        }
      }
    },
    "/patient/create": {
      "post": {
        "tags": ["Patient"],
        "summary": "Create new patient",
        "parameters":[{
          "in": "body",
          "required":["name", "surname", "phone"],
          "description": "Create new patient",
          "schema": {
            "properties": {
              "telegram_id": {
                "type": "string"
              },
              "subscription_id": {
                "type": "string"
              },
              "name": {
                "type": "string",
                "maxLength": 255
              },
              "surname": {
                "type": "string",
                "maxLength": 255
              },
              "phone": {
                "type": "string",
                "maxLength": 13
              },
              "address": {
                "type": "string",
                "maxLength": 255
              },
              "birth_date": {
                "type": "string",
                "maxLength": 25
              },
              "gender": {
                "type": "string",
                "maxLength": 10
              }
            },
            "example": {
              "address":"Toshkent, Yakkasaroy, 12/22",
              "name":"Michael",
              "surname":"Jeckson",
              "birth_date":"03.09.1990",
              "gender":"male",
              "phone":"+998999994561"
            }
          }
        }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "data": {
                  "properties": {
                    "_id": {
                      "type": "integer",
                      "uniqueItems": true,
                      "autoIncrement": true
                    },
                    "address": {
                      "type": "string",
                      "maxLength": 255
                    },
                    "name": {
                      "type": "string",
                      "maxLength": 255
                    },
                    "surname": {
                      "type": "string",
                      "maxLength": 255
                    },
                    "birth_date": {
                      "type": "string",
                      "maxLength": 25
                    },
                    "gender": {
                      "type": "string",
                      "maxLength": 10
                    },
                    "phone": {
                      "type": "string",
                      "uniqueItems": true,
                      "maxLength": 13
                    }
                  }
                },
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "data": {
                  "id": 17,
                  "address": "Toshkent, Yakkasaroy, 12/22",
                  "name": "Michael",
                  "surname": "Jecksons",
                  "birth_date": "03.09.1990",
                  "gender": "male",
                  "phone": "+998999994561",
                  "subscription_id": "ECV1WBHLQ",
                  "updatedAt": "2022-05-23T12:36:59.957Z",
                  "createdAt": "2022-05-23T12:36:59.957Z"
                },
                "message": "Patient Michael Jecksons successfully created"
              }
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "error": "Something wrong"
              }
            }
          }
        }
      }
    },
    "/patient/by-id": {
      "get": {
        "tags": ["Patient"],
        "summary": "Get patient by ID",
        "parameters": [{
          "required":["id"],
          "in": "qeury",
          "name": "id"
        }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "_id": {
                  "type": "integer",
                  "uniqueItems": true,
                  "autoIncrement": true
                },
                "telegram_id": {
                  "type": "string"
                },
                "subscription_id": {
                  "type": "string"
                },
                "address": {
                  "type": "string",
                  "maxLength": 255
                },
                "name": {
                  "type": "string",
                  "maxLength": 255
                },
                "surname": {
                  "type": "string",
                  "maxLength": 255
                },
                "birth_date": {
                  "type": "string",
                  "maxLength": 25
                },
                "gender": {
                  "type": "string",
                  "maxLength": 10
                },
                "phone": {
                  "type": "string",
                  "uniqueItems": true,
                  "maxLength": 13
                },
                "createdAt": {
                  "type": "string"
                },
                "updatedAt": {
                  "type": "string"
                } 
              },
              "example": {
                "id": 12,
                "address": "Toshkent, Yakkasaroy, 12/22",
                "name": "Michael",
                "surname": "Jecksons",
                "birth_date": "03.09.1990",
                "gender": "male",
                "phone": "+998999994561",
                "subscription_id": "ECV1WBHLQ",
                "telegram_id":"8418231",
                "createdAt": "2022-05-23T12:34:48.000Z",
                "updatedAt": "2022-05-23T12:34:48.000Z"
              }
            }
          },
          "404": {
            "description": "Error not found",
            "schema": {
              "properties": {
                "error": {
                  "type": "string"
                }
              },
              "example": {
                "error": "Patient not found"
              }
            }
          }
        }
      }
    },
    "/pill": {
      "get": {
        "tags": ["Pill"],
        "summary": "Get all pills",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "data": {
                "type":"array",
                  "items": {
                    "properties": {
                      "_id": {
                        "type": "integer",
                        "uniqueItems": true,
                        "autoIncrement": true
                      },
                      "name": {
                        "type": "string",
                        "maxLength": 255
                      },
                      "type": {
                        "type": "string",
                        "maxLength": 255
                      }
                    }
                  }
                }
              },
              "example": {
                "data": [
                  {
                    "id": 3,
                    "name": "Trimol 50",
                    "type": "Tab",
                    "createdAt": "2022-05-20T10:09:40.000Z",
                    "updatedAt": "2022-05-20T10:09:40.000Z"
                  },
                  {
                    "id": 4,
                    "name": "Fenotropil 100",
                    "type": "Tab",
                    "createdAt": "2022-05-20T10:09:40.000Z",
                    "updatedAt": "2022-05-20T10:09:40.000Z"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Error not found",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "Error": "No doctor found"
              }
            }
          }
        }
      }
    },
    "/pill/create": {
      "post": {
        "tags": ["Pill"],
        "summary": "Create new pill",
        "parameters":[{
          "in": "body",
          "required":["name", "type"],
          "description": "Create new pill",
          "schema": {
            "properties": {
              "_id": {
                "type": "integer",
                "uniqueItems": true,
                "autoIncrement": true
              },
              "name": {
                "type": "string",
                "maxLength": 255
              },
              "type": {
                "type": "string",
                "maxLength": 255
              }
            },
            "example": {
              "name":"Fenilpiracetam",
              "type":"tab"
            }
          }
        }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "Pill Fenilpiracetam Tab successfully created!"
              }
            }
          },
          "400": {
            "description": "Validation error",
              "schema": {
                "properties": {
                  "errors": {
                  "type":"array",
                    "items": {
                      "properties": {
                        "key": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "errors": [
                    {
                      "name": "Invalid value"
                    },
                    {
                      "type": "Invalid value"
                    }
                  ]
                }
              }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "error": "Something wrong"
              }
            }
          }
        }
      }
    },
    "/pill/by-id": {
      "get": {
        "tags": ["Pill"],
        "summary": "Get pill by ID",
        "parameters": [{
          "required":["id"],
          "in": "qeury",
          "name": "id"
        }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "_id": {
                  "type": "integer",
                  "uniqueItems": true,
                  "autoIncrement": true
                },
                "name": {
                  "type": "string",
                  "maxLength": 255
                },
                "type": {
                  "type": "string",
                  "maxLength": 255
                },
                "createdAt": {
                  "type": "string"
                },
                "updatedAt": {
                  "type": "string"
                } 
              },
              "example": {
                "id": 1,
                "type": "Tab",
                "name": "Fenilpiracetam",
                "createdAt": "2022-05-24T05:07:57.000Z",
                "updatedAt": "2022-05-24T05:07:57.000Z"
              }
            }
          },
          "400": {
            "description": "Validation error",
              "schema": {
                "properties": {
                  "errors": {
                  "type":"array",
                    "items": {
                      "properties": {
                        "key": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "errors": [
                    {
                      "id": "Invalid value"
                    }
                  ]
                }
              }
          },
          "404": {
            "description": "Error not found",
            "schema": {
              "properties": {
                "error": {
                  "type": "string"
                }
              },
              "example": {
                "error": "Pill not found"
              }
            }
          }
        }
      }
    },
    "/pill/by-name": {
      "get": {
        "tags": ["Pill"],
        "summary": "Get pill by name",
        "parameters": [{
          "required":["name"],
          "in": "qeury",
          "name": "name"
        }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "_id": {
                  "type": "integer",
                  "uniqueItems": true,
                  "autoIncrement": true
                },
                "name": {
                  "type": "string",
                  "maxLength": 255
                },
                "type": {
                  "type": "string",
                  "maxLength": 255
                },
                "createdAt": {
                  "type": "string"
                },
                "updatedAt": {
                  "type": "string"
                } 
              },
              "example": {
                "id": 1,
                "type": "Tab",
                "name": "Fenilpiracetam",
                "createdAt": "2022-05-24T05:07:57.000Z",
                "updatedAt": "2022-05-24T05:07:57.000Z"
              }
            }
          },
          "400": {
            "description": "Validation error",
              "schema": {
                "properties": {
                  "errors": {
                  "type":"array",
                    "items": {
                      "properties": {
                        "key": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "errors": [
                    {
                      "name": "Invalid value"
                    }
                  ]
                }
              }
          },
          "404": {
            "description": "Error not found",
            "schema": {
              "properties": {
                "error": {
                  "type": "string"
                }
              },
              "example": {
                "error": "Pill not found"
              }
            }
          }
        }
      }
    },
    "/recept/create": {
      "post": {
        "tags": ["Recept"],
        "summary": "Create new Recept",
        "parameters":[{
          "required":["phone", "password", "name", "surname", "hospital", "doctor_type"],
          "in": "body",
          "description": "Register doctor",
          "schema": {
            "properties": {
              "pill_id": {
                "type": "integer",
                "maxLength": 255
              },
              "patient_id": {
                "type": "integer"
              },
              "doctor_id": {
                "type": "integer"
              },
              "time": {
                "type":"object",
                "start_date":"date",
                "end_date":"date"
              },
              "quantity": {
                "type": "string",
                "maxLength": 255
              },
              "description": {
                "type": "string",
                "maxLength": 255
              }
            },
            "example": {
              "pill_id": 2,
              "patient_id": 8,
              "doctor_id": 13,
              "time": {
                "start_date": "2022-06-08",
                "end_date": "2022-06-10",
                "times": ["08:00", "22:00"]
              },  
              "quantity": "2",
              "description": "Before sleep"
            }
          }
        }],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "Recept created"
              }
            }
          },
          "400": {
            "description": "Validation error",
              "schema": {
                "properties": {
                  "errors": {
                  "type":"array",
                    "items": {
                      "properties": {
                        "key": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "errors": [
                    {
                      "name": "Invalid value"
                    }
                  ]
                }
              }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "properties": {
                "error": {
                  "type": "string"
                }
              },
              "example": {
                "error": "Something wrong!  "
              }
            }
          }
        }
      }
    },
    "/visit/create": {
      "post": {
        "tags": ["Visit"],
        "summary": "Create new visit",
        "parameters":[{
          "in": "body",
          "required":["name", "type"],
          "description": "Create new visit",
          "schema": {
            "properties": {
              "patient_id": {
                "type": "integer"
              },
              "doctor_id": {
                "type": "integer"
              },
              "visit_date": {
                "type": "date"
              },
              "complaints": {
                "type": "string"
              }
            },
            "example": {
              "patient_id": 2,
              "doctor_id":  1,
              "visit_date": "08-06-2022",
              "complaints": "Uyqisizlik"
            }
          }
        }],
        "responses": {
          "201": {
            "description": "OK",
            "schema": {
              "properties": {
                "message": {
                  "type": "string"
                },
                "id": {
                  "type": "integer"
                }
              },
              "example": {
                "message": "Visit created",
                "id": 12
              }
            }
          },
          "400": {
            "description": "Validation error",
              "schema": {
                "properties": {
                  "errors": {
                  "type":"array",
                    "items": {
                      "properties": {
                        "key": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "errors": [
                    {
                      "name": "Invalid value"
                    },
                    {
                      "type": "Invalid value"
                    }
                  ]
                }
              }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "error": "Something wrong"
              }
            }
          }
        }
      }
    },
    "/visit/by-patient": {
      "get": {
        "tags": ["Visit"],
        "summary": "Get visit by patient",
        "parameters": [{
          "required":["id"],
          "in": "qeury",
          "name": "id"
        }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "id": {
                  "type": "integer"
                },
                "patient_id": {
                  "type": "integer"
                },
                "doctor_id": {
                  "type": "integer"
                },
                "visit_date": {
                  "type": "date"
                },
                "complaints": {
                  "type": "string"
                }
              },
              "example": {
                "id": 2,
                "patient_id": 2,
                "doctor_id": 1,
                "visit_date": "08-06-2022",
                "complaints": "Uyqisizlik",
                "createdAt": "2022-06-08T12:18:02.000Z",
                "updatedAt": "2022-06-08T12:18:02.000Z"
              }
            }
          },
          "400": {
            "description": "Validation error",
              "schema": {
                "properties": {
                  "errors": {
                  "type":"array",
                    "items": {
                      "properties": {
                        "key": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "errors": [
                    {
                      "name": "Invalid value"
                    }
                  ]
                }
              }
          },
          "404": {
            "description": "Error not found",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "Error": "No patient visits"
              }
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "properties": {
                "error": {
                  "type": "string"
                }
              },
              "example": {
                "error": "Something wrong!  "
              }
            }
          }
        }
      }
    },
    "/visit/doctor": {
      "get": {
        "tags": ["Visit"],
        "summary": "Get visit by doctor",
        "parameters": [{
          "required":["id"],
          "in": "qeury",
          "name": "id"
        }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "id": {
                  "type": "integer"
                },
                "patient_id": {
                  "type": "integer"
                },
                "doctor_id": {
                  "type": "integer"
                },
                "visit_date": {
                  "type": "date"
                },
                "complaints": {
                  "type": "string"
                }
              },
              "example": {
                "id": 2,
                "patient_id": 2,
                "doctor_id": 1,
                "visit_date": "08-06-2022",
                "complaints": "Uyqisizlik",
                "createdAt": "2022-06-08T12:18:02.000Z",
                "updatedAt": "2022-06-08T12:18:02.000Z"
              }
            }
          },
          "400": {
            "description": "Validation error",
              "schema": {
                "properties": {
                  "errors": {
                  "type":"array",
                    "items": {
                      "properties": {
                        "key": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "errors": [
                    {
                      "name": "Invalid value"
                    }
                  ]
                }
              }
          },
          "404": {
            "description": "Error not found",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "Error": "No doctor visits"
              }
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "properties": {
                "error": {
                  "type": "string"
                }
              },
              "example": {
                "error": "Something wrong!"
              }
            }
          }
        }
      }
    },
    "/visit/by-id": {
      "get": {
        "tags": ["Visit"],
        "summary": "Get visit by id",
        "parameters": [{
          "required":["id"],
          "in": "qeury",
          "name": "id"
        }],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "id": {
                  "type": "integer"
                },
                "patient_name": {
                  "type": "string"
                },
                "doctor_name": {
                  "type": "string"
                },
                "visit_date": {
                  "type": "date"
                },
                "complaints": {
                  "type": "string"
                }
              },
              "example": {
                "id": 2,
                "patient_name": "Tayson",
                "doctor_id": "Michael",
                "visit_date": "08-06-2022",
                "complaints": "Uyqisizlik",
                "createdAt": "2022-06-08T12:18:02.000Z",
                "updatedAt": "2022-06-08T12:18:02.000Z"
              }
            }
          },
          "400": {
            "description": "Validation error",
              "schema": {
                "properties": {
                  "errors": {
                  "type":"array",
                    "items": {
                      "properties": {
                        "key": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "errors": [
                    {
                      "name": "Invalid value"
                    }
                  ]
                }
              }
          },
          "404": {
            "description": "Error not found",
            "schema": {
              "properties": {
                "Error": {
                  "type": "string"
                }
              },
              "example": {
                "Error": "No visit"
              }
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "properties": {
                "error": {
                  "type": "string"
                }
              },
              "example": {
                "error": "Something wrong!  "
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Doctor": {
      "required": ["name", "surname", "password", "doctor_type"],
      "properties": {
        "_id": {
          "type": "integer",
          "uniqueItems": true,
          "autoIncrement": true
        },
        "name": {
          "type": "string",
          "maxLength": 50
        },
        "surname": {
          "type": "string",
          "maxLength": 50
        },
        "phone": {
          "type": "string",
          "maxLength": 50
        },
        "hospital": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "doctor_type": {
          "type": "integer"
        }
      }
    },
    "Doctor_type": {
      "required": ["type"],
      "properties": {
        "_id": {
          "type": "integer",
          "uniqueItems": true,
          "autoIncrement": true
        },
        "type": {
          "type": "string",
          "uniqueItems": true,
          "maxLength": 255
        }
      }
    },
    "Patient": {
      "required": ["name", "surname", "phone"],
      "properties": {
        "_id": {
          "type": "integer",
          "uniqueItems": true,
          "autoIncrement": true
        },
        "address": {
          "type": "string",
          "maxLength": 255
        },
        "name": {
          "type": "string",
          "maxLength": 255
        },
        "surname": {
          "type": "string",
          "maxLength": 255
        },
        "birth_date": {
          "type": "string",
          "maxLength": 25
        },
        "gender": {
          "type": "string",
          "maxLength": 10
        },
        "phone": {
          "type": "string",
          "uniqueItems": true,
          "maxLength": 13
        }
      }
    },
    "Pill": {
      "required": ["name", "type"],
      "properties": {
        "_id": {
          "type": "integer",
          "uniqueItems": true,
          "autoIncrement": true
        },
        "type": {
          "type": "string",
          "maxLength": 255
        },
        "name": {
          "type": "string",
          "maxLength": 255
        }
      }
    },
    "Recept": {
      "required": ["pill_id", "patient_id", "doctor_id", "start_date", "end_date", "quantity"],
      "properties": {
        "_id": {
          "type": "integer",
          "uniqueItems": true,
          "autoIncrement": true
        },
        "pill_id": {
          "type": "integer",
          "maxLength": 255
        },
        "patient_id": {
          "type": "integer"
        },
        "doctor_id": {
          "type": "integer"
        },
        "start_date": {
          "type": "date"
        },
        "end_date": {
          "type": "date"
        },
        "quantity": {
          "type": "string",
          "maxLength": 255
        },
        "description": {
          "type": "string",
          "maxLength": 255
        }
      }
    },
    "Visit": {
      "required": ["visit_date", "patient_id", "doctor_id"],
      "properties": {
        "_id": {
          "type": "integer",
          "uniqueItems": true,
          "autoIncrement": true
        },
        "visit_date": {
          "type": "date"
        },
        "patient_id": {
          "type": "integer"
        },
        "doctor_id": {
          "type": "integer"
        },
        "complaints": {
          "type": "date"
        }
      }
    }
  },
  "schemes": ["http"],
  "consumes": ["application/json"],
  "produces": ["application/json"]
}